controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

effort_controllers:
  ros__parameters:
    joints:
      - slider_to_cart
    interface_name: effort
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort